### ISSUE TITLE
Getting logged out of my wallet when I do a browser refresh on my accounts page

### ISSUE THREAD

**Issue by artinpetrossian** [tronscan/tronscan-frontend#366] opened 2018-07-18 03:30 UTC
Steps to reproduce:

1.  Log into tronscan.org with my private key
2. Click "Refresh" in browser (using Chrome)

Am now logged out.

**Comment by joe-meyer** [comment] 2018-07-19 19:12
Duplicate of #329

**Closed** 2018-08-23 18:04 UTC
