### ISSUE TITLE
TRON Explorer Error

### ISSUE THREAD

**Issue by bitincome** [tronscan/tronscan-frontend#120] opened 2018-06-05 03:59 UTC
Hi Tronix,
I'm sending a question about the TRON Explorer.
Into my account requesting TRX for testing at testnet says
"When requesting TRX you will receive 10000 TRX which you can use for testing on the testnet.
You may only request TRX 10 times per account."

I did request twice and got 20.000, third time shows as error.
Is correct that i can request 10 times 10.000 and it's showing error
or
it's allowed to have only 1 time 10.000 and the error was me got 20.000
???
Sending Screenshot in attachment, Thank You.

![screen shot 2018-06-04 at 11 19 09 pm tron](https://user-images.githubusercontent.com/32534834/40954604-3cc6db08-6853-11e8-8459-91118d2d87b6.png)

**Comment by bitincome** [comment] 2018-06-05 04:00
![screen shot 2018-06-04 at 11 59 55 pm](https://user-images.githubusercontent.com/32534834/40954630-6bb5ffc0-6853-11e8-8268-b58c140f5e82.png)

**Comment by Rovak** [comment] 2018-06-08 22:56
Duplicate of #112

**Closed by Rovak** 2018-06-08 22:56 UTC
