### ISSUE TITLE
Sign in /  Sign out bug

### ISSUE THREAD

**Issue by ironbeeper** [tronscan/tronscan-frontend#344] opened 2018-07-13 16:31 UTC
Once you sign out of your wallet you can sign in instantly without entering your private key.

![image](https://user-images.githubusercontent.com/17235949/42702613-514703f6-86ca-11e8-868c-7881a08bc780.png)

![image](https://user-images.githubusercontent.com/17235949/42702650-68f8bb34-86ca-11e8-9cbf-5867b6b8e147.png)

![image](https://user-images.githubusercontent.com/17235949/42702674-7c601c30-86ca-11e8-8e52-721410240f0a.png)

![image](https://user-images.githubusercontent.com/17235949/42702691-8bfb4552-86ca-11e8-9d0e-d631021f400d.png)

**Comment by joe-meyer** [comment] 2018-07-15 03:10
Duplicate of #272

**Closed** 2018-07-18 19:21 UTC

**Comment by ironbeeper** [comment] 2018-07-19 05:13
Still the same problem... Ain't fixed.

**Comment by joe-meyer** [comment] 2018-07-19 10:48
@ironbeeper did you test with the latest master branch? My guess is that the site just hasn't been updated yet with the fix and that it will go live on tronscan.org with the next release
