### ISSUE TITLE
Unconfirmed transaction / small block

### ISSUE THREAD

**Issue by Fabjoh** [tronscan/tronscan-frontend#711] opened 2018-10-17 23:11 UTC
Hello, I have an unconfirmed transaction for more than 24 hours : f08953b596a7da850b336f72aae736df3a15975be1ce8d7dc02f03daf9b36598
It seems to belong to an unconfirmed block : #3256814
Likewise I see a lots of unconfirmed blocks that are old.
Is that normal

**Comment by sanxiahaoren** [comment] 2018-10-23 07:01
already confirmed.

**Comment by i-am-vivek** [comment] 2018-12-04 10:38
I'm also facing this. I've transferred 50000 TRX using the faucet. In Blockchain, It is showing like I got all of them. But in API, I'm getting 0TRX. because the transactions have not been confirmed.

**Closed** 2019-02-16 02:37 UTC
