### ISSUE TITLE
bug in sending TRX

### ISSUE THREAD

**Issue by markfrez** [tronscan/tronscan-frontend#139] opened 2018-06-07 17:09 UTC
In my wallet I have available 0.00044 but when sending it I have available 0 trx

![screenshot-2018-6-7 tronscan bug](https://user-images.githubusercontent.com/39841827/41114849-ebe8ad8a-6a85-11e8-9c0c-b5e67ae7cb4b.png)

**Comment by markfrez** [comment] 2018-06-07 17:18
![screenshot-2018-6-7 tronscan 2](https://user-images.githubusercontent.com/39841827/41115351-8700e05c-6a87-11e8-8349-b9419c21d33d.jpg)

**Comment by Rovak** [comment] 2018-06-08 22:52
Duplicate of #85

**Closed by Rovak** 2018-06-08 22:52 UTC
