### ISSUE TITLE
Trying to burn some tokens

### ISSUE THREAD

**Issue by Darkentia** [tronscan/tronscan-frontend#121] opened 2018-06-05 07:18 UTC
Hello Team

I've been trying to burn some tokens for testing purposes and try to send to the address T000000000000000000000000000000000. But as soon as I go to SEND and paste the address, all user interface is lost, leaving me with only the background of Tronscan.
I don't know if this is intended, but I can reproduce it each time.
Please advice... thanks.

**Comment by Rovak** [comment] 2018-06-08 22:55
Duplicate of #46

**Closed by Rovak** 2018-06-08 22:55 UTC
