### ISSUE TITLE
[Bounty] Tronscan V2 - faulty loading bar

### ISSUE THREAD

**Issue by PMD3VSolution** [tronscan/tronscan-frontend#26] opened 2018-05-20 16:32 UTC
Bug Report
---
after opening the page you can see the loading bar... for several hours.
only after you reload the website it disappears

![image](https://user-images.githubusercontent.com/39301026/40280996-c589f3c0-5c5b-11e8-829b-fffb5612c930.png)

![image](https://user-images.githubusercontent.com/39301026/40280999-de316778-5c5b-11e8-9bbb-0c6b71f68392.png)

Reward Information
-----------------------
voluntary donation: 0x38C7de5ffcdF0686aCdF2Da15c38A6a7632112D8

Timestamp of the test
--------------------
20. may 2018 6:00 pm (UTC+1)

Tested OS
---------
Windows 7
Windows 10
IOS Device

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by Rovak** [comment] 2018-05-22 19:34
I'm unable to reproduce this

**Comment by Jacob8765** [comment] 2018-05-22 19:54
Yeah, I can't reproduce it either

**Comment by Rovak** [comment] 2018-06-03 21:05
Closing as non-reproducible

**Closed by Rovak** 2018-06-03 21:05 UTC
Labels: bug
